title:              Clean Blog
email:              gilsonvarghese@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
baseurl:            "/"
url:                "https://gilson27.github.io/"

# Social Profiles
twitter_username: https://twitter.com/gilsonkcym?lang=en
github_username:    https://github.com/gilson27/
medium_username:  https://medium.com/@gilsonvarghese
linkedin_username: https://www.linkedin.com/in/gilsonv/

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-171622672-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
